import { commonStyles } from '@/src/styles/common';

export const getStyles = (colors: any) => StyleSheet.create({
    container: { flex: 1 },
    header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingBottom: 15, backgroundColor: colors.card, borderBottomWidth: 1, borderBottomColor: colors.borderColor },
    headerTitle: { fontSize: 24, fontWeight: 'bold', color: colors.text },
    listContent: { padding: 15, paddingBottom: 100 },
    card: { backgroundColor: colors.card, ...commonStyles.card, ...commonStyles.shadow },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },

    goalName: { fontSize: 18, fontWeight: 'bold', color: colors.text },
    amountText: { fontSize: 16, fontWeight: '600', color: colors.text },
    deadlineText: { fontSize: 14, color: colors.subtleText, marginBottom: 10 },
    progressBarContainer: { height: 10, borderRadius: 5, overflow: 'hidden', marginBottom: 10 },
    progressBar: { height: '100%', backgroundColor: '#FF9500' },
    progressRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    progressText: { fontSize: 12 },
    adjustButtons: { flexDirection: 'row', gap: 10 },
    adjustButton: { width: 30, height: 30, borderRadius: 15, justifyContent: 'center', alignItems: 'center' },
    plusButton: { backgroundColor: '#34C759' },
    minusButton: { backgroundColor: '#FF3B30' },
    emptyText: { textAlign: 'center', marginTop: 50, fontSize: 16, color: colors.subtleText },
    modalContainer: { flex: 1, paddingTop: 20 },
    modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingBottom: 15, borderBottomWidth: 1, borderBottomColor: colors.borderColor },
    modalTitle: { fontSize: 20, fontWeight: 'bold', color: colors.text },
    modalSubtitle: { fontSize: 16, marginBottom: 15 },
    formContainer: { padding: 20 },
    label: { fontSize: 14, fontWeight: '500', color: colors.subtleText, marginBottom: 8, marginTop: 10 },
    input: { backgroundColor: colors.inputBackground, borderRadius: 10, padding: 12, fontSize: 16, color: colors.text, borderWidth: 1, borderColor: colors.borderColor },
    dateButton: {
        width: '100%',
        padding: 12,
        borderWidth: 1,
        borderRadius: 10,
        marginBottom: 15,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderColor: colors.borderColor,
        backgroundColor: colors.inputBackground
    },
    dateText: { fontSize: 16, color: colors.text },
    datePlaceholder: { fontSize: 16, color: colors.subtleText },
    datePickerContainer: {
        width: '100%',
        borderRadius: 12,
        padding: 10,
        marginBottom: 15,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: colors.borderColor
    },
    modalButtons: { flexDirection: 'row', justifyContent: 'space-between', width: '100%' },
    button: { ...commonStyles.button, flex: 1, marginHorizontal: 5 },
    cancelButton: { backgroundColor: '#FF3B30' },
    buttonText: { ...commonStyles.buttonText },
    syncContainer: { width: '100%', marginBottom: 15 },
    syncHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
    syncLabel: { fontSize: 16 },
    pickersContainer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
    pickerWrapper: { flex: 1, maxWidth: '45%' },
    pickerLabel: { fontSize: 12, marginBottom: 5 },
    pickerButton: {
        width: '100%',
        height: 50,
        borderWidth: 1,
        borderRadius: 8,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 10
    },
    pickerButtonText: { fontSize: 16 },
    pickerModalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.5)' },
    pickerModalContent: { borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingBottom: 30, maxHeight: '60%' },
    pickerModalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, borderBottomWidth: 1 },
    pickerModalTitle: { fontSize: 18, fontWeight: 'bold' },
    pickerItem: { padding: 15, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    pickerItemText: { fontSize: 16 },
    pickerItemSubtext: { fontSize: 14 },
    suggestionText: { fontSize: 14, marginBottom: 5, fontWeight: '500' },
    centeredView: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.5)' },
    modalView: { width: '80%', ...commonStyles.modalView, ...commonStyles.shadowMedium },
});
